### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by kshingler** [deprekate/PHANOTATE#10]
Showing 2 errors during install below:

git clone --recursive git@github.com:deprekate/PHANOTATE.git
Cloning into 'PHANOTATE'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

PHANOTATE-master kshingle$ make
cd fastpath && /Applications/Xcode.app/Contents/Developer/usr/bin/make
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [all] Error 2

**Comment by deprekate** [comment]
Hi, this is an issue with not having rsa keys set up for github.   You can create your own keys, or you can use the direct read-only url (which I updated in the README) with the command:

git clone --recursive https://github.com/deprekate/PHANOTATE.git
