### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by pck0** [deprekate/PHANOTATE#11]
Hello! I've been happily calling genes using phanotate but I ran across 4 genomes on NCBI that mysteriously resist my attempts: MG945313, MG945322, MK765556 and MK765660. They all give me the error pasted below. It does not have anything to do with the file name, fasta header or the file itself as far as I can tell, since changing those makes no difference. Simply adding the offending genome into a previously working file causes an error so it appears to be the nucleotide sequence? 

Traceback (most recent call last):
  File "/stor/work/Ochman/paul/PHANOTATE/phanotate.py", line 40, in <module>
    my_graph = functions.get_graph(my_orfs)
  File "/stor/work/Ochman/paul/PHANOTATE/lib/functions.py", line 354, in get_graph
    add_trnas(my_orfs, G)
  File "/stor/work/Ochman/paul/PHANOTATE/lib/functions.py", line 469, in add_trnas
    column = line.split('\t')
TypeError: a bytes-like object is required, not 'str'

**Comment by deprekate** [comment]
Hi, Im glad you like PHANOTATE.  
I just downloaded the four sequences from NCBI over the webpage interface, hence the poor file naming sequence(...).fasta.  I ran each through the newest version of phanotate, and all worked without errors (see adendum).  I ran them on an HP laptop running OSX10.9 with python version 3.7.1
I have a suspicion there is/are hidden characters in the files you have, that cause python/phanotate to think the input file is not UTF-8 (string) but instead a binary file.

How did you retrieve the four genomes?  Can you send me one of your files, and I can check it out.




```
~/master/PHANOTATE$ ls -d ~/Downloads/sequence* | xargs -i python3 phanotate.py {}
#id:	MG945322.1
#START	STOP	FRAME	CONTIG	SCORE
1	951	+	MG945322.1	-8815197.632177482709533875275	
948	1205	+	MG945322.1	-130.6493182734889174721799192	
1324	1473	+	MG945322.1	-13.26510623818247143384449253	
1518	2924	+	MG945322.1	-228455452.9021640778064585711	
2935	3456	+	MG945322.1	-7380.899944265795041409260336	
3459	3833	+	MG945322.1	-782.4083408036310295258033007	
3925	4038	+	MG945322.1	-5.824891408581877339239585888	
3998	4264	+	MG945322.1	-17.63180560936719293354392663	
#id:	MK765556.1
#START	STOP	FRAME	CONTIG	SCORE
1	1719	+	MK765556.1	-38542757.12938536950312178613	
1732	2124	+	MK765556.1	-11218.12055451420683485881935	
2213	2106	-	MK765556.1	-0.3708184693649596365373582439	
2322	3335	+	MK765556.1	-1206538.736248235036336714371	
3339	3452	+	MK765556.1	-0.4114522407506416522849560388	
3458	3652	+	MK765556.1	-2.096974113212608961363610530	
3639	3758	+	MK765556.1	-0.1211285745836416517504046950	
3739	3942	+	MK765556.1	-261.9658017250965209635683504	
3932	4138	+	MK765556.1	-25.96176163603887253210626596	
4138	4461	+	MK765556.1	-2110.299657438329370748944623	
4461	5330	+	MK765556.1	-24184305.06669575613636321292	
5333	5584	+	MK765556.1	-39.66797597474675780204785910	
#id:	MK765660.1
#START	STOP	FRAME	CONTIG	SCORE
1	1719	+	MK765660.1	-38476079.09611245466557324020	
1732	2124	+	MK765660.1	-11105.29438140119256519619221	
2280	2188	-	MK765660.1	-0.1713078195137652440440177786	
2321	3334	+	MK765660.1	-1194403.980906465864879575791	
3338	3451	+	MK765660.1	-0.4107404383721327709262845552	
3457	3756	+	MK765660.1	-6.632876532035799495418981339	
3737	3940	+	MK765660.1	-259.3310824107964147922483547	
3930	4136	+	MK765660.1	-25.70065139048282374786131624	
4136	4459	+	MK765660.1	-2089.075332622648692154899808	
4459	5328	+	MK765660.1	-23941071.57880326089022061637	
5331	5582	+	MK765660.1	-39.26901556933654189571838648	
#id:	MG945313.1
#START	STOP	FRAME	CONTIG	SCORE
1	951	+	MG945313.1	-26795749.89281265268047103619	
948	1205	+	MG945313.1	-192.4041838735374475112471357	
1324	1473	+	MG945313.1	-13.37882928450569318608695558	
1518	2924	+	MG945313.1	-1901101694.668069465730483641	
2935	3456	+	MG945313.1	-9826.146933102866567195262218	
3459	3833	+	MG945313.1	-682.6301289997474495396881935	
3925	4038	+	MG945313.1	-2.884331908635840401097738579	
3998	4264	+	MG945313.1	-17.93419139666136707657717354	

```

**Comment by deprekate** [comment]
** an interesting trend that I can tell from the output scores above is that the first and last (MG945322.1, MG945313.1) are very similar and so are the second and third (MK765556.1, MK765660.1)

**Comment by pck0** [comment]
I initially downloaded all the sequences via batch entrez and the vast majority worked, downloading directly from NCBI gives me the same error.
https://www.ncbi.nlm.nih.gov/kis/download/sequence/?db=nucleotide&id=MG945313.1

I made sure it's encoded in UTF-8, downloaded from both a mac and a windows station, tried all the variations on line endings (windows, mac, unix), same issue. Attached a failing file.  
Overall it's not a big deal since it's just a handful of sequences, it's just a bit strange to me.

[MG945313.1.txt](https://github.com/deprekate/PHANOTATE/files/3487868/MG945313.1.txt)

**Comment by deprekate** [comment]
ah, I may have tracked it down.  

It looks like it was caused because in my code I use the -b flag with tRNAscanSE to indicate 'brief' output.  However between their version 1.X and 2.0 they changed the -b flag to indicate a bed file.  It looks like the long flag, --brief, is compatible with all version.

I believe this was causing the error, in addition to me needing to explicitly decode the popen output from tRNAscanSE from bytes to string (instead of relying on default behavior)(this was an artifact left over from my original coding in python2.7).

Hopefully this fixes the error, cheers
