### ISSUE TITLE
Can you create a release with the current version?

### ISSUE THREAD

**Issue by telatin** [deprekate/PHANOTATE#16]
Doing so I can refer to the release rather than the repository, for reproducibility.

Releases page: https://github.com/deprekate/PHANOTATE/releases

Thanks!
Andrea

**Comment by carolzhou** [comment]
That’s a great idea. Thanks. Will do.

Sent from my iPhone

On Jun 1, 2020, at 9:14 AM, Andrea Telatin <notifications@github.com> wrote:

﻿

Doing so I can refer to the release rather than the repository, for reproducibility.
Thanks!
Andrea

**Comment by deprekate** [comment]
Done : )
