### ISSUE TITLE
missing phanotate_lastal_alignments.tgz

### ISSUE THREAD

**Issue by tsp-kucbd** [deprekate/PHANOTATE#22]
The alignments file is not available anymore https://edwards.sdsu.edu/data/phanotate_lastal_alignments.tgz
Is there another way of recreating the proteins?

**Comment by linsalrob** [comment]
Apologies, not quite sure what happened there. The file is restored now.

Please be aware that this archive extracts to a set of gzipped files. 

**NOTES:** 
1. The file is 12GB
2. There are 94,652 files in this directory, and so `ls` or `dir` may take a while.
