### ISSUE TITLE
Warning: tRNAscan not found, proceding without tRNA masking.

### ISSUE THREAD

**Issue by noutin2020** [deprekate/PHANOTATE#25]
Dear developer,
Thank you for making avaible this pipeline publicly.

Why this warning? Does this mean the tool cannot detect the tRNA sequence region when it is present?

Below the output on my run:

mifer@fmichodigni:~/PHANOTATE$ ./phanotate.py tests/NC_001416.1.fasta 
Warning: tRNAscan not found, proceding without tRNA masking.
#id:	NC_001416
#START	STOP	FRAME	CONTIG	SCORE
191	736	+	NC_001416	-3012.018383359018091774783529
...............

**Comment by ebueren** [comment]
I am also having this issue. My system is a bit finicky so I am wondering if it is an installation issue on my end. I am using python 3.6.12 and installed using pip3, how did you install?

Cheers!

**Comment by deprekate** [comment]
Oh, sorry for the late reply, I did not get the notification of Noutin's qestion.  

The warning just means that phanotate does not see the executable trnascan on the  $PATH variable.    It will run fine without it, its just better to have the tRNA predictions added into the genome, so that phanotate will not fit an open reading frame (ORFs) into that region of the genome.  

Since phanotate works on the assumption that there are no "empty" regions in a phage genome, it will try to fill in all parts regions with coding genes (ORFs).  So you might end up with an extra false positive gene in that region.

tRNAscan has to be installed manually.  It's a hodgepodge of perl scripts and binaries, so it doesnt install easily via pip

**Comment by deprekate** [comment]
I happen to have the perfect example open right now, with phage T4.  Shown below is a part of the T4 genome that has a bunch of tRNA (the light green boxes) interspersed in with coding genes (the red boxes).  There are also some miscRNA (the pink boxes), but currently there are no tools to predict miscRNAs. 

<img width="1312" alt="trna_masking" src="https://user-images.githubusercontent.com/1821312/180331751-534f3ef0-f6ee-4a96-ba3f-e79ed06bf14a.png">

I just ran the T4 genome through phanotate without tRNAscan (it gave me the warning) and plotted the predicted genes as gray boxes, and then overlaid them.  You can see phanotate perfectly predicts the genes, but that there are some extra (gray) boxes in the areas where the tRNAs (and miscRNAs) are.  When I rerun phanotate with tRNAscan, those false positive ORFs do not show up in the phanotate predictions.

**Comment by ebueren** [comment]
Thank you so much! I didn't realize tRNA scan was a different program -- silly of me! 

I was about to try installing it manually when I saw it recently had a bioconda route added (link: https://anaconda.org/bioconda/trnascan-se command: conda install -c bioconda trnascan-se). 

The tRNA error has gone away when I run it, so I think everything is now working correctly. 

python3 phanotate.py tests/NC_001416.1.fasta
#id:    NC_001416
#START  STOP    FRAME   CONTIG  SCORE
191     736     +       NC_001416       -3012.018383359018091774783529
751     894     +       NC_001416       -0.08318335806911516255140035423
891     2636    +       NC_001416       -10090804986.14878104583426462

**Comment by linsalrob** [comment]
This is a mistake with the bioconda recipe - it should automatically install `tRNA-ScanSE`. I will implement the solution.

**Comment by linsalrob** [comment]
This has been added to bioconda with [PR #35992](https://github.com/bioconda/bioconda-recipes/pull/35992)

**Comment by noutin2020** [comment]
Great job Ebueren!!

The following NEW packages will be INSTALLED:

  pip                conda-forge/noarch::pip-22.2-pyhd8ed1ab_0
  trnascan-se        bioconda/linux-64::trnascan-se-1.3.1-pl5.22.0_3

Dear Rob, everything is et now after updating the Bioconda recipe as recommended.

Thank you everyone for your contributions.
 
Cheers!!

**Comment by noutin2020** [comment]
No Worry Katelyn.

All is well now. Thank you!

**Comment by samalfatti** [comment]
HI!  This warning indicates that you need to download and install tRNAscanSE as it cannot locate the expected tool.






From: "Noutin F. Michodigni" ***@***.***>
Reply-To: deprekate/PHANOTATE ***@***.***>
Date: Friday, July 8, 2022 at 5:30 PM
To: deprekate/PHANOTATE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deprekate/PHANOTATE] Warning: tRNAscan not found, proceding without tRNA masking. (Issue #25)


Dear developer,
Thank you for making avaible this pipeline publicly.

Why this warning? Does this mean the tool cannot detect the tRNA sequence region when it is present?

Below the output on my run:

***@***.***:~/PHANOTATE$ ./phanotate.py tests/NC_001416.1.fasta
Warning: tRNAscan not found, proceding without tRNA masking.
#id: NC_001416
#START STOP FRAME CONTIG SCORE
191 736 + NC_001416 -3012.018383359018091774783529
...............
