### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by b-tierney** [deprekate/PHANOTATE#29]
Any chance you have multithreading implemented? If I have a single file with thousands of genomes it'd be super helpful to not have to split it into thousands of little files under the hood.

Thanks so much,
Braden

**Comment by deprekate** [comment]
Hi, I have been working on getting a new 2.0 version, but it does not include multithreading.  

An issue is that I have been dwelling on, is that I should probably treat all sequences in a fasta file as the same genome.  It would help with poorly assembly genomes.

Currently however, I treat each sequence separately, so it wouldn't be too hard to add support to run each as its own thread

**Comment by b-tierney** [comment]
Hi! Thanks for the response.

Makes sense -- I understand the desire to treat all sequences in a fasta file as the same genome, makes sense. However, I'm playing around with writing a piece of software right now that uses phanotate to call ORFs, and I wanted to allow users to submit assembled data, where a single file contains multiple genomes. So that in sense, I appreciate not having to split into potentially tens of thousands of files. But, if that were the case, GNU parallel could solve the multithreading issue I suppose.

So I'm not sure how best to proceed -- I guess for now I can just split and deal with the I/O issues, but if there is a quick spot to throw a multiprocessing command in the main script lemme know and I can try that too.

**Comment by b-tierney** [comment]
Just went with splitting the file to the number of threads available. Thanks!
